# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f6d0ba39e6fbdaef342367d3c7b471dcdf0bb3b6fae8387e37c07facff073192120cc5af05ec6e3aab61b0ac07f8cd9ea07be4e33a105a20b2efcd41f12008

test:
  secret_key_base: 7c5e9fe08bb2604114f8116f69fab1b6584f4f6d750cc49d4cdda88b40544f08904ef5a0d5388025dcefbe42aae6f504dbb19891fb6b486a6df67c05a8c5daba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
